server:
  port: 8084

spring:
  profiles:
    active: dev
  application:
    name: rental-product-service

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.rental.saas.product.entity

# 日志配置
logging:
  level:
    com.rental.saas.product: DEBUG
    com.rental.saas.product.mapper: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{50} - %msg%n"

# Actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

# Swagger配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true