spring:
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml

  cloud:
    nacos:
      discovery:
        server-addr: 43.143.163.102:8848
        namespace: develop
      config:
        server-addr: 43.143.163.102:8848
        namespace: develop
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rentalsaas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: rentalsaas
    password: rentalsaas
    
    # Druid连接池配置
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 5
      max-wait: 5000
      time-between-eviction-runs-millis: 5000
      min-evictable-idle-time-millis: 10000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            multi-statement-allow: true

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: rentalsaas
      database: 1
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms

# 日志配置
logging:
  level:
    com.rental.saas.basedata: DEBUG
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{50} - %msg%n"