server:
  port: 8090

spring:
  application:
    name: rental-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # 路由配置
      routes:
        - id: user-service1
          uri: lb://rental-user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0

        - id: user-service2
          uri: lb://rental-user-service
          predicates:
            - Path=/api/auth/**,/api/employees/**,/api/merchants/**,/api/operation/auth/**,/api/operation/merchants/**,/api/dashboard/**,/api/operation/dashboard/**,/api/operation/users/**
          filters:
            - StripPrefix=0
        
        - id: base-data-service
          uri: lb://rental-base-data-service
          predicates:
            - Path=/api/stores/**,/api/vehicles/**,/api/car-models/**,/api/operation/stores/**,/api/service-area/**,/api/operation/vehicles/**,/api/operation/car-models/**
          filters:
            - StripPrefix=0
        
        - id: product-service
          uri: lb://rental-product-service
          predicates:
            - Path=/api/car-model-products/**,/api/value-added-service-templates/**,/api/cancellation-rule-templates/**,/api/service-policy-templates/**,/api/special-pricings/**,/api/product-vehicle-relations/**
          filters:
            - StripPrefix=0

        - id: order-service1
          uri: lb://rental-order-service
          predicates:
            - Path=/api/user-orders/**
          filters:
            - StripPrefix=0
            - RewritePath=/api/user-orders(?<segment>.*), /api/orders$\{segment}
        
        - id: order-service2
          uri: lb://rental-order-service
          predicates:
            - Path=/api/orders/**,/api/rentals/**
          filters:
            - StripPrefix=0
        
        - id: payment-service
          uri: lb://rental-payment-service
          predicates:
            - Path=/api/payments/**,/api/refunds/**
          filters:
            - StripPrefix=0

        - id: pricing-service
          uri: lb://rental-pricing
          predicates:
            - Path=/api/pricing/**
          filters:
            - StripPrefix=0

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always