server:
  port: 8090

spring:
  application:
    name: rental-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # 路由配置
      routes:
        - id: user-service
          uri: lb://rental-user-service
          predicates:
            - Path=/api/auth/**,/api/users/**,/api/employees/**,/api/merchants/**,/api/operation/auth/**
          filters:
            - StripPrefix=0
        
        - id: base-data-service
          uri: lb://rental-base-data-service
          predicates:
            - Path=/api/stores/**,/api/vehicles/**,/api/car-models/**,/api/operation/stores/**,/api/service-area/**,/api/operation/vehicles/**,/api/operation/merchants/**
          filters:
            - StripPrefix=0
        
        - id: product-service
          uri: lb://rental-product-service
          predicates:
            - Path=/api/products/**,/api/pricing/**,/api/templates/**
          filters:
            - StripPrefix=0
        
        - id: order-service
          uri: lb://rental-order-service
          predicates:
            - Path=/api/orders/**,/api/rentals/**
          filters:
            - StripPrefix=0
        
        - id: payment-service
          uri: lb://rental-payment-service
          predicates:
            - Path=/api/payments/**,/api/refunds/**
          filters:
            - StripPrefix=0

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always